//! Acceptance for `llm-docs`: the crate reference and the status page are generated from sources
//! the repository already maintains, `generate --check` fails on any drift, and `provenance` binds
//! a built site to its commit.
//!
//! Source files are read at run time through `CARGO_MANIFEST_DIR`, never baked in at compile time,
//! so a binary reused from another tree cannot read that tree's pages.

use std::{
    fs,
    path::{Path, PathBuf},
    process::{Command, Output},
};

const CRATES_PAGE: &str = "website/docs/reference/crates.md";
const STATUS_DATA: &str = "website/data/status.json";
const STATUS_PAGE: &str = "website/docs/status.mdx";
const STATUS_SOURCE: &str = "docs/implementation-status.md";
const GENERATED: [&str; 3] = [CRATES_PAGE, STATUS_DATA, STATUS_PAGE];

fn repository() -> PathBuf {
    let manifest = std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    Path::new(&manifest)
        .join("../..")
        .canonicalize()
        .expect("the repository root exists")
}

fn llm_docs(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_llm-docs"))
        .args(args)
        .output()
        .expect("llm-docs runs")
}

fn text(bytes: &[u8]) -> String {
    String::from_utf8_lossy(bytes).into_owned()
}

fn read(root: &Path, relative: &str) -> String {
    fs::read_to_string(root.join(relative)).unwrap_or_else(|e| panic!("reading {relative}: {e}"))
}

fn scratch(name: &str) -> PathBuf {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR"))
        .join(format!("llm-docs-{name}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    dir
}

/// Copy `from` into `to`, leaving out build output and installed packages.
fn copy_tree(from: &Path, to: &Path) {
    fs::create_dir_all(to).unwrap();
    for entry in fs::read_dir(from).unwrap() {
        let entry = entry.unwrap();
        let name = entry.file_name();
        if ["target", "node_modules", "build", ".docusaurus"]
            .iter()
            .any(|skip| name == *skip)
        {
            continue;
        }
        let path = entry.path();
        if path.is_dir() {
            copy_tree(&path, &to.join(&name));
        } else {
            fs::copy(&path, to.join(&name)).unwrap();
        }
    }
}

/// One row of the story table in `docs/implementation-status.md`: its id and its text.
fn status_rows(source: &str) -> Vec<(String, String)> {
    source
        .lines()
        .filter_map(|line| {
            let rest = line.strip_prefix("| `")?;
            let (id, rest) = rest.split_once("` |")?;
            let detail = rest.trim().trim_end_matches('|').trim();
            Some((id.to_owned(), detail.to_owned()))
        })
        .collect()
}

#[test]
fn check_passes_on_the_repository() {
    let root = repository();
    let out = llm_docs(&["generate", "--check", "--root", root.to_str().unwrap()]);
    let stdout = text(&out.stdout);
    assert!(
        out.status.success(),
        "generate --check failed on the repository\nstdout: {stdout}\nstderr: {}",
        text(&out.stderr)
    );
    for file in GENERATED {
        assert!(
            stdout.contains(file),
            "check does not report {file}: {stdout}"
        );
    }
}

#[test]
fn generated_pages_carry_the_generator_header() {
    let root = repository();
    let crates = read(&root, CRATES_PAGE);
    assert!(
        crates.contains("<!-- generated by llm-docs, do not edit -->"),
        "{CRATES_PAGE} is not generated"
    );
    assert!(crates.contains("custom_edit_url: null"), "{CRATES_PAGE}");
    let status = read(&root, STATUS_PAGE);
    assert!(
        status.contains("{/* generated by llm-docs, do not edit */}"),
        "{STATUS_PAGE} is not generated"
    );
    assert!(status.contains("custom_edit_url: null"), "{STATUS_PAGE}");
    assert!(
        status.contains("import status from '@site/data/status.json';"),
        "{STATUS_PAGE} does not read the status data"
    );
    assert!(
        status.contains("<StatusTable data={status} />"),
        "{STATUS_PAGE} does not render the status table"
    );
}

#[test]
fn crates_page_lists_every_workspace_package() {
    let root = repository();
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let out = Command::new(cargo)
        .args([
            "metadata",
            "--no-deps",
            "--format-version",
            "1",
            "--offline",
        ])
        .arg("--manifest-path")
        .arg(root.join("Cargo.toml"))
        .output()
        .expect("cargo metadata runs");
    assert!(out.status.success(), "{}", text(&out.stderr));
    let metadata: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let page = read(&root, CRATES_PAGE);
    let packages = metadata["packages"].as_array().unwrap();
    assert!(
        packages.len() > 10,
        "cargo metadata listed {}",
        packages.len()
    );
    let mut missing = Vec::new();
    for package in packages {
        let name = package["name"].as_str().unwrap();
        if !page.contains(&format!("`{name}`")) {
            missing.push(format!("package {name}"));
        }
        if let Some(description) = package["description"].as_str()
            && !page.contains(description)
        {
            missing.push(format!("description of {name}"));
        }
        for feature in package["features"].as_object().unwrap().keys() {
            if feature != "default" && !page.contains(&format!("`{feature}`")) {
                missing.push(format!("feature {name}/{feature}"));
            }
        }
    }
    assert!(missing.is_empty(), "{CRATES_PAGE} lacks: {missing:?}");
}

#[test]
fn status_has_one_item_per_implementation_status_row() {
    let root = repository();
    let rows = status_rows(&read(&root, STATUS_SOURCE));
    assert!(rows.len() > 20, "{STATUS_SOURCE} rows: {}", rows.len());
    let status: serde_json::Value = serde_json::from_str(&read(&root, STATUS_DATA)).unwrap();
    assert_eq!(status["format"], "b10x-status/1");
    assert!(status["asOf"].as_str().is_some_and(|d| d.len() == 10));
    let items = status["items"].as_array().unwrap();
    assert_eq!(items.len(), rows.len(), "one item per row");
    for (item, (id, detail)) in items.iter().zip(&rows) {
        let label = item["label"].as_str().unwrap();
        assert!(
            !label.is_empty() && label != id,
            "row {id}: label {label:?}"
        );
        assert!(
            !label.contains(&format!("`{id}`")),
            "row {id}: story id in label"
        );
        assert!(
            item["area"].as_str().is_some_and(|a| !a.is_empty()),
            "row {id}: area"
        );
        assert!(
            item["detail"].as_str().is_some_and(|d| !d.is_empty()),
            "row {id}: detail"
        );
        let expected = if detail.starts_with("Pending") {
            "planned"
        } else {
            "shipped"
        };
        assert_eq!(item["status"], expected, "row {id}: {detail}");
    }
}

#[test]
fn check_fails_on_every_kind_of_drift() {
    let root = repository();
    let tree = scratch("drift");
    for file in ["Cargo.toml", "Cargo.lock"] {
        fs::copy(root.join(file), tree.join(file)).unwrap();
    }
    for dir in ["crates", "checks", "docs", "website/docs"] {
        copy_tree(&root.join(dir), &tree.join(dir));
    }
    let at = tree.to_str().unwrap();
    let generate = llm_docs(&["generate", "--root", at]);
    assert!(
        generate.status.success(),
        "generate: {}",
        text(&generate.stderr)
    );
    let check = || llm_docs(&["generate", "--check", "--root", at]);
    let first = check();
    assert!(
        first.status.success(),
        "check after generate: {}",
        text(&first.stderr)
    );

    // A hand edit, a missing file and a changed source each fail the check, naming the file.
    let edits = [
        (CRATES_PAGE, Drift::HandEdit),
        (STATUS_PAGE, Drift::HandEdit),
        (STATUS_DATA, Drift::Missing),
        (STATUS_DATA, Drift::SourceRowAdded),
    ];
    for (file, drift) in edits {
        let source = read(&tree, STATUS_SOURCE);
        match drift {
            Drift::HandEdit => append(&tree.join(file), "Edited by hand.\n"),
            Drift::Missing => fs::remove_file(tree.join(file)).unwrap(),
            Drift::SourceRowAdded => append(
                &tree.join(STATUS_SOURCE),
                "| `new-row` | Pending: a row added to the source. |\n",
            ),
        }
        let out = check();
        assert!(!out.status.success(), "check passed after changing {file}");
        assert!(
            text(&out.stderr).contains(file),
            "{file}: {}",
            text(&out.stderr)
        );
        fs::write(tree.join(STATUS_SOURCE), source).unwrap();
        assert!(llm_docs(&["generate", "--root", at]).status.success());
        assert!(check().status.success(), "regenerate after {file}");
    }
    fs::remove_dir_all(tree).unwrap();
}

/// One way a generated file can fall behind its source.
#[derive(Clone, Copy)]
enum Drift {
    HandEdit,
    Missing,
    SourceRowAdded,
}

fn append(path: &Path, line: &str) {
    let mut content = fs::read_to_string(path).unwrap();
    content.push_str(line);
    fs::write(path, content).unwrap();
}

#[test]
fn provenance_binds_the_site_to_its_commit() {
    let site = scratch("provenance");
    let at = site.to_str().unwrap();
    let commit = "e86f43d90b637fc2c1790f77d59efff2eb852386";
    assert!(
        !llm_docs(&["provenance", "--site", at, "--commit", commit])
            .status
            .success(),
        "a directory with no built site is refused"
    );
    fs::write(site.join("index.html"), "").unwrap();
    for bad in ["e86f43d", "0000000000000000000000000000000000000000"] {
        assert!(
            !llm_docs(&["provenance", "--site", at, "--commit", bad])
                .status
                .success(),
            "commit {bad} is refused"
        );
    }
    let out = llm_docs(&["provenance", "--site", at, "--commit", commit]);
    assert!(out.status.success(), "{}", text(&out.stderr));
    let manifest: serde_json::Value =
        serde_json::from_str(&read(&site, ".well-known/b10x-site.json")).unwrap();
    assert_eq!(manifest["schema"], "b10x-project-site/v1");
    assert_eq!(manifest["repository"], "llm");
    assert_eq!(manifest["baseUrl"], "/llm/");
    assert_eq!(manifest["commit"], commit);
    assert!(site.join(".nojekyll").is_file());
    fs::remove_dir_all(site).unwrap();
}
