//! Generates the derivable pages of the llm documentation site, checks them for drift, and binds
//! a built site to its source commit and lists its routes. The site build itself is Docusaurus.
//!
//! Three files are generated:
//!
//! - `website/docs/reference/crates.md`, from `cargo metadata --no-deps`;
//! - `website/data/status.json` (`b10x-status/1`) and `website/docs/status.mdx`, from
//!   `docs/implementation-status.md`.
//!
//! `generate --check` also checks the hand-written pages: every code block titled with an example
//! file of this crate must equal that file, and no admonition may carry a raw title.

mod crates;
mod pages;
mod routes;
mod status;

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::ExitCode,
};

use clap::{Parser, Subcommand};

/// Every failure is reported as one message and exit code 1.
pub type Result<T> = std::result::Result<T, String>;

/// The line every generated Markdown page carries directly after its front matter.
pub const HEADER: &str = "<!-- generated by llm-docs, do not edit -->";
/// The same line in an MDX page, where HTML comments are not allowed.
pub const MDX_HEADER: &str = "{/* generated by llm-docs, do not edit */}";

/// The crate reference, relative to the repository root.
pub const CRATES_PAGE: &str = "website/docs/reference/crates.md";
/// The status data, relative to the repository root.
pub const STATUS_DATA: &str = "website/data/status.json";
/// The status page, relative to the repository root.
pub const STATUS_PAGE: &str = "website/docs/status.mdx";
/// The status source the repository maintains, relative to the repository root.
pub const STATUS_SOURCE: &str = "docs/implementation-status.md";
/// Every documentation page, relative to the repository root.
pub const DOCS: &str = "website/docs";

#[derive(Parser)]
#[command(about = "Generate and check the derived pages of the llm documentation site")]
struct Cli {
    #[command(subcommand)]
    command: Action,
}

#[derive(Subcommand)]
enum Action {
    /// Regenerate the crate reference and the status page, or check them for drift.
    Generate {
        /// Write nothing; fail when a generated file is missing, stale or hand-edited.
        #[arg(long)]
        check: bool,
        /// Repository root.
        #[arg(long, default_value = ".")]
        root: PathBuf,
    },
    /// Bind a built site to its source commit: write `.well-known/b10x-site.json` and the route
    /// inventory `.well-known/b10x-routes.json` into it.
    Provenance {
        /// The built site, `website/build`.
        #[arg(long)]
        site: PathBuf,
        /// The full Git revision the site was built from.
        #[arg(long)]
        commit: String,
    },
}

/// Generated files keyed by their path relative to the repository root.
type Outputs = BTreeMap<&'static str, String>;

fn outputs(root: &Path) -> Result<Outputs> {
    let crates = crates::page(&crates::metadata(root)?)?;
    let source = read(root, STATUS_SOURCE)?;
    let record = status::parse(&source)?;
    Ok(Outputs::from([
        (CRATES_PAGE, crates),
        (STATUS_DATA, status::data(&record)),
        (STATUS_PAGE, status::page(&record)),
    ]))
}

pub(crate) fn read(root: &Path, relative: &str) -> Result<String> {
    fs::read_to_string(root.join(relative)).map_err(|error| format!("reading {relative}: {error}"))
}

/// The drift of one generated file: `None` when it is current.
fn drift(root: &Path, relative: &str, expected: &str) -> Option<String> {
    match fs::read_to_string(root.join(relative)) {
        Err(_) => Some(format!("missing {relative}")),
        Ok(found) if found != expected => Some(format!("stale or edited {relative}")),
        Ok(_) => None,
    }
}

fn generate(root: &Path, check: bool) -> Result<()> {
    let outputs = outputs(root)?;
    if check {
        let problems: Vec<_> = outputs
            .iter()
            .filter_map(|(relative, content)| drift(root, relative, content))
            .collect();
        if !problems.is_empty() {
            return Err(format!(
                "generated files have drifted ({}); run `cargo run --locked -p llm-docs -- generate`",
                problems.join(", ")
            ));
        }
        for relative in outputs.keys() {
            println!("{relative}: current");
        }
    } else {
        for (relative, content) in &outputs {
            let path = root.join(relative);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)
                    .map_err(|error| format!("creating {}: {error}", parent.display()))?;
            }
            fs::write(&path, content).map_err(|error| format!("writing {relative}: {error}"))?;
            println!("{relative}: written");
        }
    }
    let problems = pages::check(root)?;
    if !problems.is_empty() {
        return Err(format!(
            "hand-written pages fail their checks:\n  {}",
            problems.join("\n  ")
        ));
    }
    println!("{DOCS}: example blocks match their files, no raw admonition titles");
    Ok(())
}

/// The project-site publication record for one build of the `/llm/` site.
fn site_manifest(commit: &str) -> Result<String> {
    if commit.len() != 40
        || !commit.bytes().all(|b| b.is_ascii_hexdigit())
        || commit.bytes().all(|b| b == b'0')
    {
        return Err("commit must be a nonzero full Git revision".to_owned());
    }
    Ok(format!(
        "{{\n  \"baseUrl\": \"/llm/\",\n  \"commit\": \"{commit}\",\n  \"repository\": \"llm\",\n  \"schema\": \"b10x-project-site/v1\"\n}}"
    ))
}

fn write_provenance(site: &Path, commit: &str) -> Result<()> {
    let manifest = site_manifest(commit)?;
    if !site.join("index.html").is_file() {
        return Err(format!("{} holds no built site", site.display()));
    }
    let write = |path: PathBuf, content: &str| {
        fs::write(&path, content).map_err(|error| format!("writing {}: {error}", path.display()))
    };
    fs::create_dir_all(site.join(".well-known"))
        .map_err(|error| format!("creating .well-known: {error}"))?;
    let inventory = routes::inventory(site, commit)?;
    write(site.join(".well-known/b10x-site.json"), &manifest)?;
    write(site.join(".well-known/b10x-routes.json"), &inventory)?;
    write(site.join(".nojekyll"), "")
}

fn main() -> ExitCode {
    let result = match Cli::parse().command {
        Action::Generate { check, root } => generate(&root, check),
        Action::Provenance { site, commit } => write_provenance(&site, &commit)
            .map(|()| println!("{}: bound to {commit}", site.display())),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("llm-docs: {message}");
            ExitCode::FAILURE
        }
    }
}

/// Quote a value as a YAML double-quoted scalar.
pub(crate) fn yaml_string(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn provenance_refuses_anything_but_a_full_nonzero_revision() {
        let commit = "e86f43d90b637fc2c1790f77d59efff2eb852386";
        assert!(site_manifest(commit).unwrap().contains(commit));
        for bad in [
            "e86f43d",
            &"0".repeat(40),
            &format!("{}\"", &commit[..39]),
            &format!("{commit}0"),
        ] {
            assert!(site_manifest(bad).is_err(), "{bad}");
        }
    }

    #[test]
    fn yaml_strings_escape_quotes_and_backslashes() {
        assert_eq!(yaml_string(r#"a "b" \c"#), r#""a \"b\" \\c""#);
    }
}
