import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {withProductSite} from '@beyond10x/docs-system/product-site';

// `docs/reference/crates.md`, `docs/status.mdx` and `data/status.json` are generated by
// `llm-docs generate`; everything else is written by hand.
const config: Config = {
  title: 'LLM',
  tagline: 'One neutral model-inference boundary, with credentials, routing and costs kept explicit.',
  favicon: 'img/mark.svg',

  future: {
    v4: true,
  },

  url: 'https://beyond10x.github.io',
  baseUrl: '/llm/',

  organizationName: 'beyond10x',
  projectName: 'llm',
  deploymentBranch: 'gh-pages',
  trailingSlash: false,

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
    mermaid: true,
  },

  themes: ['@docusaurus/theme-mermaid'],
  plugins: [
    [
      '@docusaurus/plugin-client-redirects',
      {
        // The status overview became the generated status page.
        redirects: [{from: '/docs/status/where-this-stands', to: '/docs/status'}],
      },
    ],
  ],

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: 'docs',
          editUrl: 'https://github.com/beyond10x/llm/tree/main/website/',
        },
        blog: false,
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'LLM',
      items: [
        {to: '/docs/', label: 'Documentation', position: 'left'},
        {to: '/docs/reference/crates', label: 'Crates', position: 'left'},
        {to: '/docs/status', label: 'Status', position: 'left'},
        {href: 'https://github.com/beyond10x/llm', label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      links: [
        {
          title: 'Documentation',
          items: [
            {label: 'Overview', to: '/docs/'},
            {label: 'Getting started', to: '/docs/getting-started'},
            {label: 'The five concepts', to: '/docs/concepts/overview'},
            {label: 'Crates', to: '/docs/reference/crates'},
            {label: 'Status', to: '/docs/status'},
          ],
        },
        {
          title: 'Guides',
          items: [
            {label: 'Call a local endpoint', to: '/docs/guides/call-a-local-endpoint'},
            {label: 'Force one tool call', to: '/docs/guides/call-a-model-with-one-forced-tool'},
            {label: 'Use llm from a synchronous loop', to: '/docs/guides/use-llm-from-a-synchronous-loop'},
            {label: 'Run the checks', to: '/docs/guides/run-the-checks'},
          ],
        },
        {
          title: 'Project',
          items: [
            {label: 'Source', href: 'https://github.com/beyond10x/llm'},
            {label: 'Releases', href: 'https://github.com/beyond10x/llm/releases'},
            {label: 'Changelog', href: 'https://github.com/beyond10x/llm/blob/main/CHANGELOG.md'},
          ],
        },
      ],
      copyright: 'A beyond10x project. LLM · Apache-2.0.',
    },
  } satisfies Preset.ThemeConfig,
};

export default withProductSite(config, {landing: './product.json', mark: 'LLM'});
